name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Obtener el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Copiar todo el proyecto a la EC2
      - name: Copy entire project to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./"
          target: "/home/${{ secrets.EC2_USER }}/app"
          rm: true

      # Crear .env en la raÃ­z y desplegar con Docker Compose
      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_KEY }}
            script: |
                cd /home/${{ secrets.EC2_USER }}/app

                cat > .env << 'EOF'
                POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                POSTGRES_DB=${{ secrets.POSTGRES_DB }}

                PORT=${{ secrets.PORT }}
                JWT_SECRET=${{ secrets.JWT_SECRET }}
                DATABASE_URL=${{ secrets.DATABASE_URL }}

                VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}
                EOF

                cat > backend/.env << 'EOF'
      
                PORT=${{ secrets.PORT }}
                JWT_SECRET=${{ secrets.JWT_SECRET }}
                DATABASE_URL=${{ secrets.DATABASE_URL }}
                EOF

                cat > frontend/.env << 'EOF'
                VITE_REACT_APP_API_URL=${{ secrets.VITE_REACT_APP_API_URL }}
                EOF

                if ! command -v docker &> /dev/null
                then
                    echo "Instalando Docker..."
                    sudo apt update -y
                    sudo apt install -y docker.io docker-compose
                    sudo systemctl enable docker
                    sudo systemctl start docker
                fi

                echo "Iniciando contenedores..."
                sudo docker-compose down
                sudo docker-compose up -d --build

                echo "Despliegue completado correctamente"

