name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Copiar TODO el proyecto a la EC2
      - name: Copy entire project to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./"
          target: "/home/${{ secrets.EC2_USER }}/app"
          rm: true   # Limpia antes de copiar

      # 3. Ejecutar comandos en la EC2 para ejecutar docker compose
      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/app

            # Asegurar que Docker y Compose existen (solo 1 vez)
            if ! command -v docker &> /dev/null
            then
              echo "Instalando Docker..."
              sudo apt update -y
              sudo apt install -y docker.io docker-compose
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            echo "Iniciando contenedores..."
            sudo docker compose down
            sudo docker compose up -d --build

            echo "Despliegue completado correctamente"
